---
title: dajocarter
timezone: America/Indiana/Indianapolis
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
email: dajocarter@gmail.com
description: Hi, I'm David Carter and I'm addicted to the internet. I am currently
  the Director of Technical Services at [Tribeswell](https://tribeswell.com) where
  I develop and maintain dozens of WordPress websites.
author: David Carter
author_description: Internet junkie. Denver Broncos fan. Proud Dog Owner.
author_image: "/uploads/profile_bhufds.png"
author_bg_image: "/uploads/alexander-rotker-107460.jpg"
links:
- url: mailto:dajocarter@gmail.com
  icon: icon-envelope
  text: dajocarter@gmail.com
- url: "//github.com/dajocarter"
  icon: icon-github
  text: dajocarter
- url: "//twitter.com/dajocarter"
  icon: icon-twitter
  text: dajocarter
- url: "//instagram.com/dajocarter"
  icon: icon-instagram
  text: dajocarter
baseurl: 
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- node_modules/
- package.json
- gulpfile.js
