---
title: David Carter
timezone: America/Indiana/Indianapolis
collections:
  categories:
    title: Categories
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: projects
  values:
    layout: project
permalink: pretty
email: dajocarter@gmail.com
description: Hi, I'm David Carter and I'm addicted to the internet. I am currently
  the Director of Technical Services at Tribeswell where I develop and maintain dozens
  of WordPress websites.
author: David Carter
author_description: Director of Technical Services and Lead Developer at [Tribeswell](https://tribeswell.com).
author_image: "/uploads/profile-picture.png"
hero_image: "/uploads/hero-joshua-trees.jpg"
links:
- url: mailto:dajocarter@gmail.com
  icon: icon-envelope
  text: dajocarter@gmail.com
- url: "//github.com/dajocarter"
  icon: icon-github
  text: dajocarter
- url: "//twitter.com/dajocarter"
  icon: icon-twitter
  text: dajocarter
- url: "//instagram.com/dajocarter"
  icon: icon-instagram
  text: dajocarter
universities:
- name: Northern Illinois University
  degree_name: Master of Science in Mathematics
  degree_dates: 2011 - 2013
- name: California State University, Northridge
  degree_name: Bachelor of Arts in Mathematics
  degree_dates: 2009 - 2011
- name: Antelope Valley College
  degree_name: Associate of Science in Mathematics
  degree_dates: 2006 - 2009
baseurl:
url: https://dajocarter.netlify.com
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- node_modules/
- package.json
- gulpfile.js
